name: detad
channels:
- defaults
dependencies:
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- configparser=3.5.0=py27_0
- dbus=1.10.20=0
- decorator=4.0.11=py27_0
- entrypoints=0.2.3=py27_0
- enum34=1.1.6=py27_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- html5lib=0.9999999=py27_0
- icu=54.1=0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- jsonschema=2.6.0=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=5.1.0=py27_0
- jupyter_console=5.2.0=py27_0
- jupyter_core=4.3.0=py27_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libsodium=1.0.10=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- markupsafe=1.0=py27_0
- mistune=0.7.4=py27_0
- nbconvert=5.2.1=py27_0
- nbformat=4.4.0=py27_0
- notebook=5.0.0=py27_0
- openssl=1.0.2l=0
- pandocfilters=1.4.2=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.2.1=py27_0
- pcre=8.39=1
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.14=py27_0
- ptyprocess=0.5.1=py27_0
- pygments=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=5
- qtconsole=4.3.1=py27_0
- readline=6.2=2
- scandir=1.5=py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.5.0.1=py27_0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- tk=8.5.18=0
- tornado=4.5.2=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=3.0.2=py27_0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - appdirs==1.4.3
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - backports.weakref==1.0rc1
  - cycler==0.10.0
  - funcsigs==1.0.2
  - h5py==2.7.0
  - ipdb==0.10.3
  - ipython-genutils==0.2.0
  - joblib==0.11
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - markdown==2.6.8
  - matplotlib==2.0.2
  - mock==2.0.0
  - numpy==1.13.0
  - packaging==16.8
  - pandas==0.20.2
  - pbr==3.1.1
  - prompt-toolkit==1.0.14
  - protobuf==3.3.0
  - pyparsing==2.2.0
  - pytz==2017.2
  - scikit-learn==0.18.2
  - scipy==0.19.1
  - seaborn==0.8.1
  - sklearn==0.0
  - subprocess32==3.2.7
  - tensorflow-gpu==1.2.1
  - tqdm==4.15.0
  - uuid==1.30
  - webencodings==0.5.1
  - werkzeug==0.12.2
prefix: /home/humam/anaconda2/envs/detad

